# Configurações de conexão (localhost pois o Spring está rodando fora do Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog
spring.datasource.username=admin
spring.datasource.password=senha_segura_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update

# Para ver o SQL no console (muito útil em dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita erros com tipos LOB/Postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true