# Configurações de banco de dados para Produção (Render)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update vai atualizar a estrutura das tabelas se elas não existirem no DB do Render
# Quando o banco estiver estabilizado, é recomendável mudar para 'validate' ou 'none'
spring.jpa.hibernate.ddl-auto=update

# Esconde os logs de SQL em produção para melhorar performance
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
