INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());INSERT INTO category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO category (name, created_At) VALUES ('Computadores', NOW());